### ISSUE TITLE
incremental-refresh-about.md - claim on query folding is not entirely accurate

### ISSUE THREAD

**Issue by lbendlin** [TabularEditor/TabularEditorDocs#17]
https://github.com/TabularEditor/TabularEditorDocs/blob/main/te3/tutorials/incremental-refresh-about.md

claims that incremental refresh requires query folding.  While desirable, it is not required.  You can achieve successful incremental refresh with custom queries as well if they incorporate the RangeStart/RangeEnd parameters.   Dataflows can also do successful incremental refresh of file data based partitions (these may not be as efficient though).

**Comment by otykier** [comment]
Cc @data-goblin
