### ISSUE TITLE
Power BI plans that support Incremental refresh

### ISSUE THREAD

**Issue by gvggvg** [TabularEditor/TabularEditorDocs#18]
Wouldn't it be helpful if a clear list of Power BI plans that support Incremental refresh had been provided? Even Microsoft themselves get confused if asked this question.

**Comment by data-goblin** [comment]
@gvggvg In my opinion, it's not the scope of the article to go into licensing details regarding Power BI. 

_That said, do you refer to something like the below?_

- Supported on Pro for Datasets (not Hybrid Tables)
- Supported on PPU / Premium for Dataflows
- Supported on PPU / Premium for Data Marts
- Supported on PPU / Premium for Hybrid Tables

**Comment by gvggvg** [comment]
@data-goblin Sure there is no need to go into licencing details. Simple list of plans supporting Incremental refresh will help the article to be understandable to much wider audience, wouldn't it? Something like you listed in your post.

**Comment by data-goblin** [comment]
The purpose of the article is to inform about Incremental Refresh as a function of data modeling with Tabular Editor. Discussion of Power BI plans (licensing) is better left to Microsoft Docs. Even for the above list, it creates a situation where we have to update whenever this changes for Power BI. 

To illustrate, there are a lot of nuances when it comes to what Power BI plans (licenses) support incremental refresh:
- Power BI Service type (Report Server / Embedded / Cloud)
- Artifact Type (Datasets, Dataflows, Data Marts)
- Artifact Sub-type (Import models, Composite models, models created in the service [via data discovery / Excel files)
- Incremental Refresh Type (Import, Hybrid)

So while I appreciate the perspective that it can be helpful to a wider audience, it doesn't fit in the scope of this documentation.
