### ISSUE TITLE
Where is Appendix A?

### ISSUE THREAD

**Issue by rudzimj** [TabularEditor/TabularEditorDocs#2]
Page https://docs.tabulareditor.com/te2/Advanced-Scripting.html and https://docs.tabulareditor.com/te3/features/csharp-scripts.html both refer to **_Appendix A_**, which doesn't seem to exist. I'm guessing it's a work in progress? Is there a workaround until the doc is created?

**Comment by otykier** [comment]
This is an oversight on our part. You can find an older version of the source code reference [here](https://github.com/TabularEditor/TabularEditor/wiki/TabularEditor.TOMWrapper/9b4a05d03c40e1ae9672b69cc1225cab32c562d3). We're working on getting it updated.

More details in [this thread](https://github.com/TabularEditor/TabularEditor3/issues/305).

**Comment by rudzimj** [comment]
Perfect. Thanks. Is this an appropriate place to ask "how to" questions on scripting or is there a better place?

**Comment by otykier** [comment]
We prefer to keep this repo for questions related to the docs. If you want to ask a question on the product itself, for example if you need scripting assistance, please go here:

- [Tabular Editor 2.x](https://github.com/TabularEditor/TabularEditor/issues)
- [Tabular Editor 3.x](https://github.com/TabularEditor/TabularEditor3/discussions)

**Comment by otykier** [comment]
We’ve updated the Appendix A links to point to our new API docs: https://docs.tabulareditor.com/api/index.html
