### ISSUE TITLE
official Best Practice Rules

### ISSUE THREAD

**Issue by rootsmusic** [TabularEditor/TabularEditorDocs#3]
Shouldn't the Github link be updated to https://github.com/microsoft/Analysis-Services/tree/master/BestPracticeRules in the following docs?

- [ ] The [last paragraph](https://github.com/TabularEditor/TabularEditorDocs/blob/main/te2/Best-Practice-Analyzer.md/#official-best-practice-rules).
- [ ] The last paragraph under "[Adding additional collections](https://github.com/TabularEditor/TabularEditorDocs/blob/main/te2/Best-Practice-Analyzer-Improvements.md/#adding-additional-collections)".

**Comment by mlonsk** [comment]
Will be fixed with #55 
Thank you for reporting

**Comment by rootsmusic** [comment]
Sorry @mlonsk, the link should be https://github.com/microsoft/Analysis-Services
