### ISSUE TITLE
Link fejl

### ISSUE THREAD

**Issue by bluehenve** [TabularEditor/TabularEditorDocs#41]
Hej

Den er død:
![image](https://user-images.githubusercontent.com/70111241/231851811-ac61a6b9-41a3-4c36-8ed5-dc4a5a496949.png)

![image](https://user-images.githubusercontent.com/70111241/231851782-8f092b30-f467-4a69-b3c2-a4bf796de98e.png)

Mvh - Henrik 😊

**Comment by otykier** [comment]
Thanks - links have been fixed now :)

**Comment by bluehenve** [comment]
👍

Med venlig hilsen

Henrik Vestergaard
Power BI udvikler
***@***.*** ***@***.***>  | +45 50 15 52 99
henrikBLUEvestergaard | www.henrikv.dk<http://henrikv.dk/>  |  CVR 42753262

________________________________
Fra: Daniel Otykier ***@***.***>
Sendt: 2. maj 2023 09:42
Til: TabularEditor/TabularEditorDocs ***@***.***>
Cc: Henrik Vestergaard ***@***.***>; Author ***@***.***>
Emne: Re: [TabularEditor/TabularEditorDocs] Link fejl (Issue #41)


Thanks - links have been fixed now :)
